logging:
  pattern:
    file: '%d [%level] %c{1.} [%t] %m%n'
    console: '%d [%level] %c{1.} [%t] %m%n'
  level:
    com:
      bookingservice: TRACE
  file:
    name: appLog.log
eureka:
  instance:
    hostname: localhost
server:
  port: '9002'
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/culturofestodb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: booking-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
