eureka:
  instance:
    hostname: localhost
server:
  port: '9002'
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/culturofestodb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: booking-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
