eureka:
  instance:
    hostname: localhost
server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: admin-service
        uri: lb://admin-service
        predicates:
        - Path=/api/admin/**
      - id: event-service
        uri: lb://event-service
        predicates:
        - Path=/api/event/**
      - id: home-service
        uri: lb://home-service
        predicates:
        - Path=/api/home/**